JTeUY1ZZ Setup React project
atlp-rwanda/incredible-phantom-frontend pull request #1
Opened 2020-12-30 14:47 UTC by KundwaBruno

### What does this PR do?
This PR sets up the initial react project
### Description of Task to be completed?

- The project is configured from scratch using Wepack and Babel
- Setup react router and create a dummy route `"/"` for the landing page
- Added a readMe file which includes installation and run commands
- SCSS has been added as our choice of CSS framework

### How should this be manually tested?

- Run `npm install` to install all dependecies.
- Run `npm run dev` to start your application.

### Relevant Trello card

ID: JTeUY1ZZ

2020-12-31 10:46 UTC, mansurissa approved these changes
Nice Job

2021-01-02 15:58 UTC, samuel776 approved these changes

2021-01-04 10:49 UTC, SIBONIYO approved these changes
Great Job Bruno and the team!

2021-01-05 13:15 UTC, raymond42 requested changes
attend to the comment and revert to me

2021-01-05 13:47 UTC, raymond42 commented on .eslintcache
> +[{"/Users/andela/Desktop/phantom-frontend/incredible-phantom-frontend/src/index.js":"1","/Users/andela/Desktop/phantom-frontend/incredible-phantom-frontend/src/router/App.js":"2","/Users/andela/Deskt
can we stop tracking this file? you can put it in `.gitignore` file

2021-01-05 14:47 UTC, raymond42 approved these changes
LGTM

2021-01-05 15:10 UTC, merged