Fix Issues
atlp-rwanda/incredible-phantom-frontend pull request #16
Opened 2021-01-20 17:35 UTC by KundwaBruno

### What does this PR do?
This PR fixes issues #13  #14 #15
### Task to be completed

- Add description to the application
- Add auto language detection
- Change the redirect button's label from `redirect` to` back to home`

### How to test
**Testing language auto detection**

- Change your browser's language to your desired language between english french or kinyaRwanda.
- Close the phantom application session/Tab and re open it.
- Phantom will be displayed in the user preferred browser language.

2021-01-20 19:30 UTC, ceelogre requested changes
Titles should be translated according to language settings.

![Capture d’écran 2021-01-20 à 21 24 07](https://user-images.githubusercontent.com/5022823/105225033-a9e3c300-5b66-11eb-97f8-749996b69295.png)

2021-01-20 19:30 UTC, ceelogre commented on public/index.html
> +    <title>Phantom | Public transport made easir</title>
Typo in `easier`

2021-01-21 07:58 UTC, raymond42 submitted a review, later dismissed
Looks good to me

2021-01-21 10:39 UTC, raymond42 approved these changes

2021-01-21 10:58 UTC, ceelogre approved these changes

2021-01-21 10:59 UTC, merged