Assigning Buses to Drivers
atlp-rwanda/incredible-phantom-frontend pull request #31
Opened 2021-02-15 13:08 UTC by 41hulk

### What does this PR do?
• Assign Driver to Buses
### Description of Task to be completed?
• Appropriate error messages are displayed on unsuccessful attempts
• Authenticated users are able to assign bus to drivers.
• Skeleton UIs/screen are/is shown when the page loads/is loading.
• The app layouts are displayed
• The page is responsive.
### How should this be manually tested?
• checkout this branch
• run npm install
•  click on a row 
• click add bus to a Driver
### What are the relevant trello id?
bD45iW2U
Labels
work in progress

2021-02-16 12:45 UTC, GuevaraMarius approved these changes, later dismissed

2021-02-16 13:42 UTC, GuevaraMarius submitted a review, later dismissed

2021-02-16 13:44 UTC, mansurissa submitted a review, later dismissed
LGTM!

2021-02-16 15:21 UTC, raymond42 commented on src/components/AssignBusToDriver/assignDriver.js
> +                {/*footer*/}
remove commented line

2021-02-16 15:22 UTC, raymond42 commented on src/components/AssignBusToDriver/assignDriver.js
> +                <label for="cars">Choose a car:</label> */}
remove these commented lines

2021-02-16 15:25 UTC, raymond42 commented on src/components/AssignBusToDriver/assignDriver.js
> +                      {data.firstName}
let' use es6 destructuring to get firstName, lastName and the busId . i.e `const {firstName, LastName, budId} = data`

2021-02-16 15:27 UTC, raymond42 commented on src/redux/actionCreators/assignAction.js
> +        .get('https://incredible-phantom.herokuapp.com/api/users',{
we stored this url in a constant called `BACKEND_URL` you can import it and use it

2021-02-16 15:32 UTC, raymond42 commented on src/tests/redux/actionCreators/assignDriverAction.test.js
> +        // expect(calledActions[1].type).toEqual(GET_BUS_FAILED);
remove this commented line

2021-02-16 15:33 UTC, raymond42 requested changes
Good work at @41hulk . Only a few comments to attend to

2021-02-16 15:33 UTC, raymond42 commented
and also you need to squash your commits to one commit

2021-02-17 14:01 UTC, raymond42 approved these changes

2021-02-17 14:04 UTC, merged